### ISSUE TITLE
Edited evolves lose levels on evolution

### ISSUE THREAD

**Issue by chikorissa** [AdAstra-LD/DS-Pokemon-Rom-Editor#51] opened 2024-05-12 21:48 UTC
I edited the evolution level for Beedrill and Foretress and upon evolution for both these mons, they go down in level. Examples:

Kakuna --> lv. 13 --> Beedrill --> lv. 10 (Kakuna evolved into Beedrill at lv 13 (my edit) but when it evolved Beedrill fell to lv 10)

Pineco --> lv. 20 --> Foretress --> lv. 17 (Pineco evolved into Foretress at lv 20 (my edit) but when it evolved Foretress fell to lv 17)

The first case made me think that the mon just reverted to the lv it usually evolves at without edit, but pineco normally evolves at lv 31 this doesn't seem to be the case. Other mons that I've edited didn't see this happen

**Comment by AdAstra-LD** [comment] 2024-05-12 21:52
Can you add a screenshot of the evolution editor open on both Kakuna and Beedrill, please?
Also Pineco and Forretress if you can.

**Comment by chikorissa** [comment] 2024-05-12 22:12
Just replied by email, let me know if you got it!

**Comment by chikorissa** [comment] 2024-05-12 22:21
![beedrill](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/169618934/63ba68e2-2f82-455e-a43f-bff5776ac2be)
![foretress](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/169618934/59381b13-454e-4718-a7b5-59c9647077f5)
![kakuna](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/169618934/d131b63a-00a6-4ddc-a10a-be155efcddfa)
![pineco](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/169618934/3138fb68-f330-46a8-9943-d85054ea8342)

**Comment by Mixone-FinallyHere** [comment] 2024-05-15 09:18
@chikorissa did you edit their Growth Rates ?

The only explanation that makes sense here is that the amount of exp at those levels matched a lower level with a different growth curve. FOr reference:
![image](https://github.com/AdAstra-LD/DS-Pokemon-Rom-Editor/assets/11949750/a903d465-1562-4d70-bab8-e67efa983368)

Possible combos that make level 13 Kakuna become level 10 Beedrill:
Fluctuating Kakuna becomes Medium-Fast Beedrill
Medium-SLow Kakuna becomes Slow Beedrill
Medium-Fast Kakuna becomes Erratic Beedrill

Possible combos that make level 20 Pineco become level 17 Forretress:
Fast Pineco becomes Slow Forretress
Medium-Slow Pineco becomes Medium-Fast Forretress
Fluctuating Pineco becomes Medium-Fast Forretress

Since the evolution table does not affect the exp curves either you made some of these modifications (I may have missed some) or something else happened, but likely it is not the actual evolution editor itself the cause.

**Comment by chikorissa** [comment] 2024-05-15 12:55
That must be it! Good catch

**Comment by Mixone-FinallyHere** [comment] 2024-05-15 16:34
So to be 100% sure that we can close this, did you do make edits such as those?

**Comment by Mixone-FinallyHere** [comment] 2024-05-16 13:54
Can you please close the issue in that case?

To avoid it happening often I am adding an alert to at least make people aware

**Comment by AdAstra-LD** [comment] 2024-05-16 19:11
Marked as invalid and closing since it isn't an issue with the tool.

**Closed by AdAstra-LD** 2024-05-16 19:11 UTC
Labels: invalid
